### ISSUE TITLE
Another language of the same name

### ISSUE THREAD

**Issue by hazama-yuinyan** [willtim/Expresso#10]
Hi! This is not an issue of the code, but can be a problem in the future in other aspect.
I've been developing [a language](https://gitlab.com/exsgo/expresso-lang) of exactly the same name as yours. And I just published it at [a custom domain](https://www.expresso-lang.org) about a week ago. This shouldn't be a problem immediately and I'm just informing you of that fact.

**Comment by willtim** [comment]
Thanks for the heads up. I've had this repository name since 2012, so I'm not going to volunteer to change the name :)  I think the target audience of both projects is sufficiently different that hopefully little confusion will arise (assuming my project has anything that even closely resembles an "audience").

**Comment by hazama-yuinyan** [comment]
I don't think having the same name will become a problem(like trademarks?) and even think that I should avoid those situations, this wouldn't be a problem currently and in the future. I'd like to co-exist with your project ;-) Thank you.
