### ISSUE TITLE
Incomplete inferring for if expressions?

### ISSUE THREAD

**Issue by FrankBro** [willtim/Expresso#9]
```haskell
λ> let div = n d -> if d == 0 then DivBy0 {} else Ok (n / d)
λ> :type div
forall r. (r\Ok) => Int -> Int -> <DivBy0 : {}, Ok : Int | r>
```
Shouldn't the type of `div` be
```haskell
forall r. (r\Ok\DivBy0) => Int -> Int -> <DivBy0 : {}, Ok : Int | r>
```
I noticed that if I swap `Ok` and `DivBy0`, I get
```haskell
λ> let div = n d -> if d == 0 then Ok (n/d) else DivBy0 {}
λ> :type div
forall r. (r\DivBy0) => Int -> Int -> <Ok : Int, DivBy0 : {} | r>
```

**Comment by willtim** [comment]
Hi, I'm on holiday at the moment, but will try to take a look soon. This is indeed a bug and it was probably introduced by the rank-2 types support introduced by commit dedfae157. I will keep you posted!

**Comment by willtim** [comment]
Hi, I found the issue. If you look at line 164 in the file src/Expresso/Type.hs there is a TODO because I knew this line was wrong at the time I wrote it (I was intending to prune the substitution map elsewhere). If you change the line to read "Just t  -> apply s t", the issue will be fixed. I will commit a proper fix when I get back from holiday and add some more tests. Many thanks!

**Comment by willtim** [comment]
I've committed a quick fix via the github web UI:  https://github.com/willtim/Expresso/commit/ea82773874c7f4f1594a7becfcdc1c376660d92e

**Comment by willtim** [comment]
Test case for this pushed
